name: Deploy Snake Game to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Run daily

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Generate Snake game
      uses: Platane/snk@v3
      with:
        github_user_name: anitakanayo6
        outputs: |
          dist/github-contribution-grid-snake.svg
          dist/github-contribution-grid-snake-dark.svg
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
